Build neovim nightly on download failure
rhysd/action-setup-vim pull request #18
Opened 2021-09-30 06:29 UTC by glacambre

As described in the commit message, Neovim is often failing to publish nightly releases these days. When this happens, it would be nice to have action-setup-vim fall back to building neovim. I know that you said in https://github.com/rhysd/action-setup-vim/issues/9 that you thought there wasn't much of point to doing this as when Neovim fails to publish a nightly release this means that HEAD is broken, but I think the situation has changed since this comment. Indeed, as described in https://github.com/neovim/neovim/issues/15709 , the recent failures are caused by Neovim's CI failing to publish artifacts that built fine. In this case, building Neovim is a perfect workaround.

This commit implements building neovim nightly in case of download failures on linux. If you are okay with this approach, I'll try to implement OSX and Windows support.

2021-09-30 14:45 UTC, rhysd requested changes

2021-09-30 14:45 UTC, rhysd commented on src/neovim.ts
> +    await exec('git', ['clone', '--depth=1', 'https://github.com/neovim/neovim', dir]);
It'd be better to install dependencies in this function so that user don't always need to install them. Installing packages via apt-get takes time because many network requests happen. I think avoiding them as much as possible would be great.

```typescript
await exec('sudo', ['apt-get', 'install', '-y', 'ninja-build', 'gettext', 'libtool', 'libtool-bin', 'autoconf', 'automake', 'cmake', 'g++', 'pkg-config', 'unzip', 'curl']);
```

2021-09-30 14:45 UTC, rhysd commented on src/install_linux.ts
> +                core.debug(`Neovim download failure: ${e.message}.`);
```suggestion
                const err = const err = ensureError(e);
                core.debug(`Neovim download failure: ${err.message}.`);
```

`ensureError()` is necessary to make TypeScript compiler happy.

2021-09-30 14:45 UTC, rhysd commented on src/neovim.ts
> +    await exec('make', ['-j', `CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=${installDir}`], opts);
```suggestion
    await exec('make', ['-j', `CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=${installDir}`, 'CMAKE_BUILD_TYPE=RelWithDebug'], opts);
```

Please add `CMAKE_BUILD_TYPE`. Otherwise it builds Neovim with debug mode.

2021-10-01 10:16 UTC, rhysd requested changes

2021-10-01 10:16 UTC, rhysd commented on src/neovim.ts
> +        ['-j', `CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=${installDir}`, 'CMAKE_BUILD_TYPE=RelWithDebug'],
```suggestion
        ['-j', `CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=${installDir} -DCMAKE_BUILD_TYPE=RelWithDebug`],
```

Ah, my suggestion was wrong.

2021-10-01 10:51 UTC, rhysd approved these changes

2021-10-01 10:52 UTC, rhysd commented
Thank you for the updates. Looks good now.

2021-10-01 10:52 UTC, merged

2021-10-01 10:53 UTC, rhysd commented
I'll add some small follow up (e.g. add tests)

2021-10-01 13:12 UTC, rhysd commented
I added tests for this. And I also added the similar logic for macOS. Now it can fallback to building Neovim from source on macOS also.

https://github.com/rhysd/action-setup-vim/commit/2acc82130462293622774258e1e5b77bfbb53509

2021-10-01 17:37 UTC, glacambre commented
Great, thank you for taking care of all this - I planned on doing it myself but had little time to do it :).

2021-10-02 14:53 UTC, rhysd commented
This feature was included in new release v1.2.8.

2021-10-02 15:00 UTC, glacambre commented
I can confirm that it works! https://github.com/glacambre/firenvim/pull/1211/checks?check_run_id=3776935994#step:9:138

Thanks a lot for this wonderful action :).

2021-10-02 15:03 UTC, rhysd commented
Yes, Neovim nightly release failed yesterday actually so we can confirm the fallback logic works fine 💯